# Generated by Django 4.2 on 2025-10-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('core', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingpoint',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='trackingpoint',
            old_name='recorded_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='trackingpoint',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.race'),
        ),
        migrations.AlterField(
            model_name='trackingpoint',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.runner'),
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Runner',
        ),
    ]
